import { ROUTES_CONFIG as CONFIG } from './routes';
import { ROUTE } from './routes.types';

export const ROUTES_LIST: ROUTE[] = [
    ROUTE.CREATURE_PROFILE,
    ROUTE.DASHBOARD,
    ROUTE.HOME,
    ROUTE.INTERNAL_SERVER_ERROR,
    ROUTE.NOT_FOUND,
    ROUTE.LOGIN,
    ROUTE.LOBBIES,
    ROUTE.LOBBY,
    ROUTE.MINTCAP_STATISTICS,
    ROUTE.PROFILE,
    ROUTE.REFERRALS,
    ROUTE.REGISTER,
    ROUTE.REGISTER_STEP2,
    ROUTE.REGISTER_STEP3,
    ROUTE.REGISTER_STEP4,
    ROUTE.REWARD_POOL,
];

export const ROUTES_CONFIG = CONFIG.filter(({ name }) => ROUTES_LIST.includes(name));
